### ISSUE TITLE
Absences

### ISSUE THREAD

**Issue by jonaspews** [python-webuntis/python-webuntis#17]
Hello,

I found your project and would like to combine it with an absence mailing script I wrote in Python. Is there any way to get the absences of the day via the API?

I'm rather new to the whole API thing, so I have not that much experience with handling/reading the data.

Thanks, Jonas

**Comment by pintman** [comment]
I don't know what you mean by "absence" but there is a [status code in PeriodObject](https://python-webuntis.readthedocs.io/en/latest/objects.html#webuntis.objects.PeriodObject) with a possible value of "cancelled" which might be right for you.

**Comment by AugustH** [comment]
Hi, took some time

I have an experimental version at
https://github.com/AugustH/python-webuntis/tree/new_calls2

This version includes access to the absences - feedback welcome.

       for ab in s.timetable_with_absences(start=today, end=datetime.datetime.now()):
            print("abs:", ab, ab.start, " -- ", ab.end, ab.teachers, ab.subject, "|", repr(ab))

**Comment by HimbeerDonald** [comment]
Hi,
I am currently trying to writa a code to automatically get the abcense ratio to all of the lessons that took place. But I am unable to get read/get the abcenses to further process them. At the moment I reset my code so the abcenses just show 0, as the information for the abcenses can not be found where the code is currently searching. 
I already tried implementing the abcense functions of the API but can't get them to work and dont know why.

Is there anybody that is able to help?

Sorry for the code format, I tried my best but it never showed up right in the preview.
The code currently is as followed:

`import webuntis
from datetime import datetime

# WebUntis credentials
username = ''
password = ''
school = ''
server = ''  # Use the base domain only

# Establish connection to WebUntis
session = webuntis.Session(
    server=server,
    username=username,
    password=password,
    school=school,
    useragent='Python WebUntis Client'
)

try:
    # Log in to WebUntis
    session.login()

    # The ID of the desired student (replace 12345 with the correct ID from the print output)
    student_id = 12345  # Replace this with the actual ID of the student

    # Define start and end date
    start_date = datetime(2024, 9, 10)
    end_date = datetime(2024, 11, 7)

    # Retrieve lessons for the desired student
    lessons = session.timetable(start=start_date, end=end_date, student=student_id)

    # Calculate total duration and absences
    total_lesson_duration = 0
    total_absence_duration = 0

    print("Lessons during which the student was absent:")

    for lesson in lessons:
        lesson_duration = (lesson.end - lesson.start).total_seconds()
        total_lesson_duration += lesson_duration

        # Check if lesson was marked as absence
        if getattr(lesson, 'code', None) == 'absence':  # Ensure 'code' attribute exists
            total_absence_duration += lesson_duration
            lesson_date = lesson.start.date()
            print(f"Absent on {lesson_date} from {lesson.start.time()} to {lesson.end.time()}")

    # Calculate ratio
    if total_lesson_duration > 0:
        absence_ratio = (total_absence_duration / total_lesson_duration) * 100
    else:
        absence_ratio = 0

    # Print results
    print(f"\nTotal lesson duration: {total_lesson_duration / 3600:.2f} hours")
    print(f"Total absence duration: {total_absence_duration / 3600:.2f} hours")
    print(f"Absence ratio: {absence_ratio:.2f}%")

finally:
    # Log out from WebUntis
    session.logout()
`

**Comment by AugustH** [comment]
there is a `session.timetable_with_absences()` to be used instead of `session.timetable()`.

btw: intead of the `try ... finally` you could use
```
with webuntis.Session(...).login() as session:
   ...
```

**Comment by HimbeerDonald** [comment]
Thanks for the quick response.
I have now changed the influenced code as followed:
`    # Unterrichtsstunden für den gewünschten Schüler abrufen
    lessons = session.timetable(start=start_date, end=end_date, student=student_id)

    # Abwesenheitsstunden für den gewünschten Schüler abrufen
    absence_lessons=session.timetable_with_absences(start=start_date, end=end_date)
    
    # Gesamtdauer und Abwesenheiten berechnen
    total_lesson_duration = 0
    total_absence_duration = 0

    print("Unterrichtsstunden, an denen der Schüler abwesend war:")

    # Anwesenheitsdauer setzen
    for lesson in lessons:
        lesson_duration = (lesson.end - lesson.start).total_seconds()
        total_lesson_duration += lesson_duration
        
    # Abwesenheitsdauer setzen    
    for lesson in absence_lessons:
        lesson_duration = (lesson.end - lesson.start).total_seconds()
        total_absence_duration += lesson_duration
        lesson_date = lesson.start.date()
        print(f"Abwesend am {lesson_date} von {lesson.start.time()} bis {lesson.end.time()}")`

Bur now I get the following fault:
webuntis.errors.RemoteError: no right for getTimetableWithAbsences()

Does that have to do with anything on my end with programming or is this a restriction set by the school which can not be influenced?

**Comment by AugustH** [comment]
the webuntis-api rights are nit easy to understand. You will have to ask your untis-admin if she gives you these rights --  hint: mention that the api is all *read only*, you won't change anything.
