### ISSUE TITLE
Returns HTML Page content on login

### ISSUE THREAD

**Issue by Jan200101** [python-webuntis/python-webuntis#18]
When using this code

import webuntis

`s = webuntis.Session(
    server='arche.webuntis.com/WebUntis',
    username=username,
    password=password,
    school='BK-Ostvest',
    useragent='WebUntis Test'
)`

this part runs just fine and the username, password, school and server are all valid
`s.login()`
but running this just prints a the servers HTML content and does not log me in

checking the HTML content it prints it shows no sign of a login in the untis array

I have tried doing the same with port 8080 too
but it just ends up with a 
`A connection attempt failed because the remote station did not respond properly after a certain amount of time, or the connection made failed because the connected host did not respond`

**Comment by pintman** [comment]
What about changing the server address to ``https://arche.webuntis.com``. Does this solve you problem?

**Comment by Jan200101** [comment]
No it does not.
It still returns the contents of a HTML page

**Comment by Jan200101** [comment]
Issue seems to have been solved in a recent commit
closing
