### ISSUE TITLE
Get timetable of one student without getStudents().filter

### ISSUE THREAD

**Issue by MatthiasReumann** [python-webuntis/python-webuntis#20]
*Hey,*

Right now it's not possible to get only the timetable of one person because some schools do not allow students to get all student-usernames.
```no right for getStudents()```

Is it possible to implement that I can give an username as parameter of the timetable method?
e.g          ```session.timetable(student="firstname.lastname", ....)```

*Thanks!*

**Comment by AugustH** [comment]
did this work out? if not: there is an unimplemented call "getPersonId" in the API (which could be implemented..)

**Comment by MatthiasReumann** [comment]
Hey! I solved the problem quit dirty...
```
def getStudentId(id, config):
    session = requests.Session()
    
    req = session.get('https://{}/WebUntis/api/public/timetable/weekly/pageconfig?type=5'.format(config.server),
                cookies = {'JSESSIONID': id})
    
    req_json = json.loads(req.text)
    
    return req_json['data']['elements'][0]['id']
```

I figured out that the userid of a student is somewhere in the response of this request.

**Comment by AugustH** [comment]
I created a branch "search" in my personal Repo:
https://github.com/AugustH/python-webuntis/commit/75f6bb5753aadac385552ddf12ca43f16d0b3e6a

could you check if session.get_student(...) works for you?
