### ISSUE TITLE
filtering students by klasse

### ISSUE THREAD

**Issue by hstop** [python-webuntis/python-webuntis#21]
Hi,

I'm trying to create an absence list per Klasse and can't figure out how to get students filtered by Klasse.
How do I relate the students to their Klasse?

Thanks

**Comment by AugustH** [comment]
Sadly the api does not  supply the "Klasse" in the students info. 

What you can try:

- studentGroup could give a hint if your admin created them systematically
- you can try to get the timetable for the student and use the information found there

**Comment by hstop** [comment]
For both way I don't understand how this could work. I don't find any related classes or function in the documentation. Can be more precisely, please?

**Comment by AugustH** [comment]
sorry, it is called "student_group" -- it gives something like "AM_1AI_TEA" (subject_class_teacher), i think this is auto generated.

or try this: get the student id and use this for the timetable for this student, there is a "klassen"-attribute
        a = one entry of timetable_with_absences
        sid = a.student.id
        print(f"  student {sid}")
        stt = sess.timetable(start=..., end=..., student=sid)
        print(f"  klassen {stt[0].klassen}")

**Comment by hstop** [comment]
Thank you for your help. We added groups retrospectively and it works so far.
Is there a reason why "Klassen" are not available in absences? Is this the choice of the creator of the API or are they not available in Untis?

In the data stream for the absences the is an "excuseStatus" - how do I access it in python?

In general, why are the objects in the stream different from the classes in Python? (I'm new in Python)

**Comment by hstop** [comment]
excuseStatus works - thanks for your efforts

is there a documentation available for the official API?

When using a filter, are the data filtered server-sided or by Python on the client? I'asking because I'm surprised that even for only one student_group 55MB of data is downloaded when processing the absences.

**Comment by AugustH** [comment]
you can get the official API by contacting the untis-hotline

> When using a filter, are the data filtered server-sided or by Python

The filtering is done in the Python code.

The python code does some caching, but only for *internal* calls to the API. You can force more caching by adding `use_cache` as a parameter to session (cache everything). Or use `from_cache=True` to your calls.
And maybe increase the `cachelen` when creating the session.
