### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by Jan200101** [python-webuntis/python-webuntis#23]
is there any method to fetch homework?

**Comment by pintman** [comment]
Maybe the Session.exams() method can provide this. However we do not use
this feature and therefore I am unable to test this.



https://python-webuntis.readthedocs.io/en/latest/session.html#webuntis.Session.exams

**Comment by Jan200101** [comment]
exams seem to be wrong
> webuntis.errors.RemoteError: no right for getExams()

the official untis app and the rewrite of BetterUntis fully support it so I suspect there to be some endpoint thats not implemented yet

**Comment by AugustH** [comment]
as it says: no right

exams is implemented, sadly the official untis app uses another (unofficial) api.

**Comment by AugustH** [comment]
I looked at https://github.com/SapuSeven/BetterUntis

app/src/main/java/com/sapuseven/untis/data/connectivity/UntisApiConstants.kt

      const val METHOD_GET_USER_DATA = "getUserData2017"

This method is NOT covered in the "official" documentation.

**Comment by Jan200101** [comment]
according to the them himself in [Issue #4](https://github.com/SapuSeven/BetterUntis/issues/4) it uses mobile.webuntis.com instead resulting in a POST request like this
`https://mobile.webuntis.com/ms/app<id>?m=getTimetable2017`

**Comment by Jan200101** [comment]
the BetterUntis developer has created a API reference which includes the (gethomework2017)[https://github.com/SapuSeven/BetterUntis/wiki/Untis-Mobile-API-Reference#gethomework2017] method
