### ISSUE TITLE
How to use api without login?

### ISSUE THREAD

**Issue by tabacha** [python-webuntis/python-webuntis#25]
Hi,
the "Goethe Schule" in Hamburg-Harburg is not using an login. 

You can access the plan without:
https://stundenplan.hamburg.de/WebUntis/?school=hh5070#/basic/timetable

How do I use the python api?

I tried:

```
s = webuntis.Session(
    server='stundenplan.hamburg.de',
    school='hh5070',
    useragent='WebUntis Test'
).login()
```

**Comment by AugustH** [comment]
Seems the API only supports authenticated access. Tried empty user/password and tried to remove the user from the request -- no success, sorry.

I think you will have to ask your untis-admin to create an account for you.

**Comment by tabacha** [comment]
Tank you for testing.
