### ISSUE TITLE
Regarding the doc Intro Example

### ISSUE THREAD

**Issue by kazanderpersson** [python-webuntis/python-webuntis#26]
Double checking: Are this server & sample school/credentials supposed to work live, or are they simply just a placeholder example? Installed the webuntis module, but got a bunch of connection errors/exceptions from the s.login() statement. But before I'm starting to figure out why

```
import webuntis

s = webuntis.Session(
    server='webuntis.grupet.at:8080',
    username='api',
    password='api',
    school='demo_inf',
    useragent='WebUntis Test'
)

s.login()

for klasse in s.klassen():
    print(klasse.name)

s.logout()
```

I'm working on getting an account to access with from our local administrator, but thought to have something to play with in the meanwhile

Thanks, and thanks for providing!

**Comment by AugustH** [comment]
Sorry, only placeholders. You will have to wait for your account.

**Comment by kazanderpersson** [comment]
Ok!
