### ISSUE TITLE
ExamObject.klassen always empty

### ISSUE THREAD

**Issue by svencan** [python-webuntis/python-webuntis#29]
Hello,

I successfully fetched exams with the library. When I print the exam, I receive the following output:
```
{'id': 5756, 'classes': [312], 'teachers': [235], 'students': [1567, 1536, 1560, 1568, 1600, 1537, 1545, 1585, 1538, 1562, 1570, 1602, 1650, 1563, 1571, 1548, 1541, 1565, 1550, 1590], 'subject': 197, 'date': 20200708, 'startTime': 1000, 'endTime': 1140}
```

However, when I print exam.klassen, it prints an empty list: ``[]``

My current workaround is to fetch the objects with the IDs from ``exam._data['classes']`` which works fine.

I use version 0.1.12:

```
cat requirements.txt | grep webuntis
webuntis==0.1.12
```

Thank you for your work.

**Comment by AugustH** [comment]
I cannot reproduce this. 

Actually `exam.klassen` is not that complicated:

        return self._session.klassen(from_cache=True).filter(
            id=set(self._data[u'classes'])
        )

which is the same as your workaround? the only difference could be in the usage of the cache -- the default is *no cache* for user calls, *use cache* for internal calls. So i could be a cache problem. 

Some things you could try:
* fill the cache before you access the exams: `dummy = mysession.klassen()`, does this fix the problem
* try a `print("cache", mysession.cache.keys())` before and after -- is the key `('klassen', frozenset())`  included?

Does any of this tips work/help?
