### ISSUE TITLE
Question: Get the info text

### ISSUE THREAD

**Issue by TheGreyDiamond** [python-webuntis/python-webuntis#30]
Hello, is there a way to get theses "News", sometimes called MOTD from the webuntis api?

**Comment by AugustH** [comment]
sorry, not with this api -- the untis app is using another, undocumented api. Maybe the links in issue #23 may help, but that api isn't neither supported nor documented...

**Comment by TheGreyDiamond** [comment]
The untis app?

**Comment by AugustH** [comment]
https://play.google.com/store/apps/details?id=com.grupet.web.app

**Comment by TheGreyDiamond** [comment]
Okay, I was looking through stuff and found the untis name for it: "News widget", I found this documentation which supports getting that feature https://noim.me/WebUntis/WebUntis.html I will play around with it. But maybe it helps

**Comment by TheGreyDiamond** [comment]
I wrote a small example, which will get news, https://gist.github.com/TheGreyDiamond/934a812abc55864e71886e1928295346   (my school code: `_Z3ltX3JlbXNjaGVpZA==`) Not perfect, but it works. No need to provied a password nor a user
