### ISSUE TITLE
TypeError at Session.exams 

### ISSUE THREAD

**Issue by littlegamer757** [python-webuntis/python-webuntis#31]
With ``untis`` being my Session object, the line
``exams = untis.exams(untis.schoolyears().current.start, untis.schoolyears().current.end)``
raises the following error:
``TypeError: inner() takes 1 positional argument but 3 were given``. 
I am not sure whether my lack of knowledge (this is my first project in python) or the wrapper is to blame, so I'm sorry if the solution is obvious. Any help is appreciated!

**Comment by AugustH** [comment]
please use "named args" e.g. start=...

      exams = untis.exams(start=untis.schoolyears().current.start, end=untis.schoolyears().current.end)

**Comment by littlegamer757** [comment]
Thank you very much, I didn't realize I had to do that.
