### ISSUE TITLE
Read "Teaching content"/"Details of the period"

### ISSUE THREAD

**Issue by tenklo** [python-webuntis/python-webuntis#32]
Hi!

I'm working on a project and need to read the field "Teaching content" and maybe even "Details of the period".

As far as I understood, these should be part of the class "webuntis.objects.PeriodObject", but are not implemented.

Is it possible to add these?

Cheers
tenklo

**Comment by AugustH** [comment]
As far as i know all (used and documented) fields of `PeriodObject` are implemented. There is are some additional fields which which seems never to be filled out.
if you try `repr(po)` of a `PeriodObject` you should see all the information. if there is some unsupported information/field its easy to implement, just post the output here.

**Comment by AugustH** [comment]
oops, there seems to be an "customizable" version of the `timetable` -- which seems to give the information you are looking for. 
could you try to use the version or just the files objects.* and session.* from (my personal version) https://github.com/AugustH/python-webuntis/tree/master/webuntis

**Comment by tenklo** [comment]
I'm sorry, I really expected to get some kind of notification and didn't check in manually until now...

What do you mean by "customizable"?
I did try your `timetable_extended` version, which did offer some additional information.

The output of `print(repr(po))` was:

> PeriodObject({'id': xxx, 'date': 20210316, 'startTime': 1450, 'endTime': 1535, 'code': 'cancelled', 'kl': [{'id': xxx}], 'te': [{'id': xxx}], 'su': [{'id': xxx}], 'ro': [], 'lsnumber': 216700, 'substText': 'Entfall', 'sg': 'xxx', 'activityType': 'Unterricht'})

Sadly the information I'm looking for is not in there.

Did I misunderstand you or is there anything else we could try?

**Comment by AugustH** [comment]
sadly this is all you get -- the _official_ API gives no more info. The webuntis app uses another undocumented interface. There are some tools which use the _reverse engineered_ api, example BetterUntis.
