### ISSUE TITLE
JSON Error message is output if the DateNotAllowed Error is catched

### ISSUE THREAD

**Issue by IsAvaible** [python-webuntis/python-webuntis#33]
I'm using the API to fetch the timetable as far as possible from WebUntis (usually up to around 3 weeks in the future). To validate whether the Date is allowed, I'm catching the exception webuntis.errors.DateNotAllowed and breaking the loop afterwards. Unfortunately, an error message is still output in the form:

```
{'jsonrpc': '2.0', 'id': '2021-03-08 10:58:06.437821', 'error': {'message': 'no allowed date', 'code': -7004}}
```

I don't think this is intentional and that's why I'm opening this issue. If there is another way that I do not know yet, I would be happy to receive an answer.

To reproduce:
```python
# .. Set up the Session object
with s.login() as s:
    monday = datetime.date.today() - datetime.timedelta(days=datetime.date.today().weekday()) 

    while True: # Wrapping loop
        friday = monday + datetime.timedelta(days=4)
        try:
            tt = s.timetable(klasse=s.klassen().filter(name="11Q2")[0], start=monday, end=friday)
        except webuntis.errors.DateNotAllowed: # Error Message is output anyway
            break
        # .. Code that interacts with the timetable

        monday += datetime.timedelta(days=7)
```

**Comment by AugustH** [comment]
I tried your example, and it seems that the value sent as `code` is the key here. I get

    ... 'error': {'message': 'startDate and endDate are not within a single school year.', 'code': -8507}}

This `code` is mapped to the different exceptions. Actually `-7004` should be `DateNotAllowed`. 
And as an _important_ issue it is logged as an error, which is usually printed to `stderr`. So you have to configure your logging to ignore these messages (or change `webuntis/utils/remote.py` line 130). From deep inside of webuntis it is hard to know if the exception will be caught and shouldn't be printed.

Remarks: something like  `while monday < s.schoolyears().current.end:` should work without the exception.
Or without loop (get timetable for 3 weeks):

```python
    yearend = s.schoolyears().current.end
    start = datetime.date.today()
    if start > yearend.date():
        sys.exit(99)
    end = start + datetime.timedelta(days=21)
    end = min(end, yearend.date())
```

**Comment by IsAvaible** [comment]
I think it's actually caused by the fact that my school only ever re-uploads the timetable weekly.
Error message when using Webuntis from the browser: "`The timetable may not be displayed for the week of 29/03/2021.`" (translated from German).

Changing up the function to always return the timetable for the next three weeks will likely not work, because my school isn't particular consistent with the weeks one is allowed to see in advance.

But, thanks for pointing me to line 130. Commenting out `log('error', result_body)` does the job.
