### ISSUE TITLE
[BUG] PeriodObject.teachers resulting in KeyError

### ISSUE THREAD

**Issue by XilefTech** [python-webuntis/python-webuntis#35]
When I try to access the `teachers` variable of a PeriodObject gained from a timetable, I get a `KeyError` exception on the key `'te'`.

So is this just broken and there is an other way to access the teachers of a given lesson or is it outright impossible to get the teachers?

**Comment by AugustH** [comment]
Very strange, should work.

Each webuntis-object holds an internal `_data` attribute -- the raw data received from the server. Could you check if the `te` is missing in all periodobjects?

```python
    p = tableRaw[0]
    print("data", p._data)
```
should give something like:

    data {'id': 1725530, 'date': 20211014, 'startTime': 1415, 'endTime': 1505, 'kl': [{'id': 928}], 'te': [{'id': 215}], 'su': ...

`teachers` uses the ids in `te` field to get the teacher-objects with that ids.

**Comment by AugustH** [comment]
Never seen this problem. 
The only idea i have: some problem with the rights. The documentation just says "rights: timetable view for the requested element". Maybe your local untis admin can help you with the rights or another account. Or the Untis forum (german only? https://forum.untis.at/)
