### ISSUE TITLE
Get teachers name from ID

### ISSUE THREAD

**Issue by TheGreyDiamond** [python-webuntis/python-webuntis#36]
I have a teachers id from a subject, now I want to know their name. I tried this and it fails with "no permission":
```py
sessionY.teachers().filter(id=myLess.teachers[0].id)[0]
```

**Comment by AugustH** [comment]
`session.teachers()` actually reads all the teachers (into the cache) and then tries to find the one with the given `id`. Seems your account lacks the right to read the teachers list --
the permissions in this api are "a little bit weird"; so you will have to ask your admin for the right to get the teachers list: could be named something like `masterdata teachers read for all`.

btw. you can do something like `myLess.teachers[0].full_name` -- which does the same as your sample call -- and gives the same error ;-((

**Comment by TheGreyDiamond** [comment]
Okay, really weird. I guess I'll ask on monday. However BetterUntis for Android is able to display teacher names, with the same account....

**Comment by AugustH** [comment]
there is "the official" api (used by python-webuntis/) and a reverse engineered api (=the one from the webuntis app) -- and the are very different in all aspects

**Comment by TheGreyDiamond** [comment]
Ahh okay good to know
