### ISSUE TITLE
Pull statusdata from specific lessons (c.g. first lesson of monday)

### ISSUE THREAD

**Issue by LogicalFreeze** [python-webuntis/python-webuntis#37]
How can I pull the statusdata/colorcode from a lesson of my timetable or pull a timetable with statusdata instead of subjects?

Thank you in advance!

**Comment by AugustH** [comment]
i am not quite sure if i understand your question right. 

There is `session.statusdata()` with gives some colors. And there is a _lot of_ color info in the data, for example

```python
   table = session.timetable(...)
   for time, row in table:
        for date, cell in row:
            for period in cell:
                for s in period.subjects:
                    ... s.backcolor, s.forecolor
                for r in period.rooms:
                    ... r.backcolor, r.backcolor
```
just look for `ColorInfo` and sub-classes of `ColorMixin` in `webuntsi/objects.py`

**Comment by LogicalFreeze** [comment]
When I use statusdata, there are like all data from all the subjects in the timetable. I dont see an id for the exact lesson. How can I get information like the code (c.g. 'code' = cancelled) from one specific lesson of the timetable, there is statusdata().period_codes[i] where I can get which codes are being used by the school, but how can I get the code of for example the first lesson of a date?

**Comment by AugustH** [comment]
in my sample above: there is `period.code`
