### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by Rekutor** [python-webuntis/python-webuntis#38]
```
webuntis\utils\remote.py", line 13, in <module>
    import requests
```

yea...

**Comment by AugustH** [comment]
yes, `requests` is an external (the only one) dependency. How did you install  `python-webuntis`

**Comment by Rekutor** [comment]
downloaded via zip.
should i use pip install instead?

**Comment by AugustH** [comment]
either `pip` (preferred) or install `requests` via package manager or via pip.

**Comment by Rekutor** [comment]
thanks it worked, thank you for responding so fast.
very cool
