### ISSUE TITLE
no right for timetable

### ISSUE THREAD

**Issue by Rekutor** [python-webuntis/python-webuntis#39]
Yea got another issue:
`webuntis.errors.RemoteError: no right for timetable`
Anyway is there something i can do about that?

**Comment by AugustH** [comment]
you need the right to view the timetable, you will have to ask your admin. And ask for more/all `read ... right`, the permissions are a little bit complicated.

**Comment by Rekutor** [comment]
"your need the right to view the timetable"
Yea well i do have it, atleast i can access the timetable via browser, so shouldnt i have the permissions to view it?

**Comment by AugustH** [comment]
no - the untis app and the browser use another api, with other permissions...

**Comment by Rekutor** [comment]
And that is?

**Comment by AugustH** [comment]
undocumented and unsupported.

there are project using that api - google for betterUntis.

**Comment by Rekutor** [comment]
Dont quite understand what your trying to tell me.


> "no - the untis app and the browser use another api, with other permissions..."

do you mean *different api's or is there really another api beside the mobile and browser version?


> "undocumented and unsupported." 

ok


> "there are project using that api - google for betterUntis."

what api are they using?

**Comment by AugustH** [comment]
`python-webuntis` is using one api, a little bit documented and supported. `python-webuntis` is just *a little* wrapper around this json-rpc calls. And this api is `read-only`.

The untis app and the web app use a different api -- not even sure if both use the same (undocumented) api. And maybe betterUntis uses also that api.

*different* means: different protocol, different permissions, different servers(?)

**Comment by Rekutor** [comment]
still doesnt explain why i apperantly dont have the right to view the timetable, although i can view it via webuntis app/browser.
What causes the permission problem? If i talk to the admin, what should i tell him? That i dont have the right to view it? If i wanna talk to them i really should be more specific with my problem.
