### ISSUE TITLE
Authentication fails above version 0.1.20 but works on 0.1.12

### ISSUE THREAD

**Issue by kuflierl** [python-webuntis/python-webuntis#45]
```
{'jsonrpc': '2.0', 'id': '2023-01-15 16:06:39.620358', 'error': {'message': 'bad credentials', 'code': -8504}}
Traceback (most recent call last):
  File "/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/utils/remote.py", line 123, in _parse_result
    return result_body[u'result']
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/session.py", line 93, in login
    res = self._request('authenticate', {
  File "/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/session.py", line 120, in _request
    data = rpc_request(self.config, method, params or {})
  File "/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/utils/remote.py", line 91, in rpc_request
    return _parse_result(request_body, result_body)
  File "/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/utils/remote.py", line 125, in _parse_result
    _parse_error_code(request_body, result_body)
  File "/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/utils/remote.py", line 143, in _parse_error_code
    raise exc
webuntis.errors.BadCredentialsError: bad credentials
```

**Comment by AugustH** [comment]
I did a *small* change because of problems with special characters in the password

in `webuntis/session.py` around line 95 
old:
`    'password': password,`
new:
`    'password': json.dumps(password)[1:-1], ### TODO: ????`
 
Could you revert that change locally (`/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/session.py`) and try again?

If it works: Do you have any special characters (non-ascii) in the password? could you check and give me a hint which character is changed by `json.dumps()` ? try something like:
`     python -c "import json; pw='abc'; print(pw, json.dumps(pw))"`

**Comment by kuflierl** [comment]
> I did a _small_ change because of problems with special characters in the password
> 
> in `webuntis/session.py` around line 95 old: ` 'password': password,` new: ` 'password': json.dumps(password)[1:-1], ### TODO: ????`
> 
> Could you revert that change locally (`/home/kuflierl/.local/lib/python3.10/site-packages/webuntis/session.py`) and try again?
> 
> If it works: Do you have any special characters (non-ascii) in the password? could you check and give me a hint which character is changed by `json.dumps()` ? try something like: ` python -c "import json; pw='abc'; print(pw, json.dumps(pw))"`

Our password has a super awkward character that isn't even in the extended ASCII charset... That would be the problem...

**Comment by kuflierl** [comment]
Random question @AugustH. Where is the line ` 'password': json.dumps(password)[1:-1], ### TODO: ????`? I can't seem to locate it in the repository in all the latest commits but it is included in the pypy package...
