### ISSUE TITLE
get Homeworks

### ISSUE THREAD

**Issue by JustLutz** [python-webuntis/python-webuntis#49]
Hi, I want to ask if there is a method to get the homework?

**Comment by AugustH** [comment]
No, sorry the official API has no support. The App uses some other, undocumented API to get this info.

**Comment by crimsdings** [comment]
homework just returns a json from 
https://euterpe.webuntis.com/WebUntis/api/homeworks/lessons?startDate=20240101&endDate=20240131

**Comment by crimsdings** [comment]
just for clarification of somebody is in search of a solution just for homeworks - you can use the jsessionid from this library but you need your schoolname id string - i took it from the cookie from https://euterpe.webuntis.com/WebUntis/api/homeworks/

`import webuntis

s = webuntis.Session(
    server='webuntis.grupet.at:8080',
    username='api',
    password='api',
    school='demo_inf',
    useragent='WebUntis Test'
)

s.login()

cookies = {'schoolname':"cookieschoolnamestring", 'JSESSIONID':s.config['jsessionid']}

r = requests.get('https://euterpe.webuntis.com/WebUntis/api/homeworks/lessons?startDate=20240101&endDate=20240131', cookies=cookies).json()

for x in r['data']['homeworks']:
    print(x)

s.logout()`

**Comment by JustLutz** [comment]
> just for clarification of somebody is in search of a solution just for homeworks - you can use the jsessionid from this library but you need your schoolname id string - i took it from the cookie from https://euterpe.webuntis.com/WebUntis/api/homeworks/
> 
> `import webuntis
> 
> s = webuntis.Session( server='webuntis.grupet.at:8080', username='api', password='api', school='demo_inf', useragent='WebUntis Test' )
> 
> s.login()
> 
> cookies = {'schoolname':"cookieschoolnamestring", 'JSESSIONID':s.config['jsessionid']}
> 
> r = requests.get('https://euterpe.webuntis.com/WebUntis/api/homeworks/lessons?startDate=20240101&endDate=20240131', cookies=cookies).json()
> 
> for x in r['data']['homeworks']: print(x)
> 
> s.logout()`

thanks for your help this solution works.

**Comment by crimsdings** [comment]
> Is there an option to read the next class tests via the REST API?

if you look at https://github.com/python-webuntis/python-webuntis/issues/49#issuecomment-1916249549 you see a solution

**Comment by crimsdings** [comment]
> Is there an option to read the next class tests via the REST API?

same way i did the homework above - you need the student id etc

`def get_exams(server, schoolname, sessionid):
    """Fetch homework from WebUntis."""
    start_date = datetime.date.today() - datetime.timedelta(days=DATE_OFFSET_PAST)
    end_date = datetime.date.today() + datetime.timedelta(days=DATE_OFFSET_FUTURE)

    # Ensure the server URL doesn't end with a slash
    server = server.rstrip('/')

    # Construct the URL for fetching homework data
    # https://euterpe.webuntis.com/WebUntis/api/exams?startDate=20250401&endDate=20250430&studentId=0000&withGrades=true&klasseId=-1
    url = (
        f"{server}/api/exams?"
        f"startDate={start_date.strftime('%Y%m%d')}"
        f"&endDate={end_date.strftime('%Y%m%d')}"
        f"&studentId=0000&withGrades=true&klasseId=-1"
    )

    # Set cookies
    cookies = {
        'schoolname': schoolname,
        'JSESSIONID': sessionid,  # The session ID to authenticate the request
    }

    # Make the GET request to the WebUntis API
    response = requests.get(url, cookies=cookies)

    # Check if the request was successful
    if response.status_code != 200:
        print(f"Failed to fetch homework. Status Code: {response.status_code}")
        print(f"Response Text: {response.text}")
        return {}

    # Return the JSON response if the request was successful
    return response.json()`

**Comment by crimsdings** [comment]
if you go to https://euterpe.webuntis.com/student-exams after logging in with your browser you will see that there is a request to 

https://euterpe.webuntis.com/WebUntis/api/exams?startDate=20250901&endDate=20250930&studentId=YOURSTUDENTID&withGrades=true&klasseId=YOURCLASSID


yourclassid is probably -1
