### ISSUE TITLE
Matching room and teacher IDs to readable names

### ISSUE THREAD

**Issue by TechClusterHQ** [python-webuntis/python-webuntis#50]
I've been trying to match the IDs provided by getTimetable() to the human friendly readable names provided by getRooms and getTeachers. I have tried matching using the order that the API supplies the values in but have not had success yet.

```json
{
    "id": 0000000,
    "date": 20230630,
    "startTime": 1105,
    "endTime": 1150,
    "kl": [
        {
            "id": 1450
        }
    ],
    "te": [
        {
            "id": 340
        }
    ],
    "su": [
        {
            "id": 136
        }
    ],
    "ro": [
        {
            "id": 33
        }
    ],
    "activityType": "Unterricht"
},
```

**Comment by TechClusterHQ** [comment]
Now resolved:

```py
print(s.rooms().filter(id=33)[0])
```

Prints the room name of the room by the name of 33.

Apologies!

**Comment by AugustH** [comment]
should be easier 😁

e.g. a Timetable is kind of list of PeriodObject and has the properties rooms and teachers which are also lists and have a name property. If you look webuntis/objects.py around line 355 you will find code with looks like your solution.

Hint: try autocompletion in your IDE, this should show the available stuff
