### ISSUE TITLE
get teacher name

### ISSUE THREAD

**Issue by mathisdt** [python-webuntis/python-webuntis#53]
Hi!
First of all, thanks for this library! It makes using WebUntis much easier. :+1: 

My question: Is there a possibility to load teacher data by the ID? Perhaps I just didn't find it... I don't have the right to call `getTeachers` but can use the person search - I tested successfully with a student. Weirdly `get_teacher()` seems to find nothing, even with names which are really existent at the school. Was there maybe an API change which is unreflected in this project? Or did I miss something?

Edit: It seems that the web app of WebUntis uses a request like this to load all data at once, including teacher names buried deep in some `elements` list with type=2:
`https://neilo.webuntis.com/WebUntis/api/public/timetable/weekly/data?elementType=5&elementId=327&date=2024-01-08&formatId=1` - I couldn't find a similar call in python-webuntis. Is it there? If so, how do I use it?

**Comment by AugustH** [comment]
You could try to override `teachers()` in your `session`-object  and return an List of Teachers with  `_data`  set with appropriate values.

The web app of WebUntis is using a different, undocumented API.

**Comment by mathisdt** [comment]
Nevermind, I'm using the undocumented API now ([reference](https://github.com/mathisdt/webuntis-fetcher)). There I get everything in one request, which (for me) outweighs the occasional need to follow changes of the undocumented API.
