### ISSUE TITLE
Clearing cached results

### ISSUE THREAD

**Issue by Jan-Weigang** [python-webuntis/python-webuntis#56]
Hi there,

I am trying to write a flask server that uses this module, so first of all I am very greatful for it!
I have figured out that the lazy-property does some caching in the background:

I have gotten timetables, listed all "subject.name"s with a for loop. 
I then get another timetable from a different teacher and log out of the session.
Then I listed this teachers subject.names again with a for loop. 

The first loop results in a get.subjects() request which then caches the resulting subjectlist. Further calls do not again require connections.
So independently from the session and connection stuff gets cached and calls minimized. So far so dandy. But how do I clear that cache?

From what I can understand the lazy-property class just caches inside the module since i never declared a variable for the get.subjects() call. So if my server is running and then the list gets updated server-side... how do I clear that cache to avoid wrong results?

`
class lazyproperty(object):
    """A read-only @property that is only evaluated once. Only usable on class
    instances' methods.

    Stolen from http://www.reddit.com/r/Python/comments/ejp25/cached_property_decorator_that_is_memory_friendly/
    """

    def __init__(self, fget, doc=None):
        self.fget = fget
        self.__doc__ = doc or fget.__doc__
        self.__name__ = fget.__name__

    def __get__(self, obj, cls):
        if obj is None:  # pragma: no cover
            return self
        obj.__dict__[self.__name__] = result = self.fget(obj)
        return result`

**Comment by AugustH** [comment]
see https://python-webuntis.readthedocs.io/en/latest/session.html

you can
* clear the cache
* use `from_cache` to request new data
* create a new session with has a new cache - not quite sure how long a login is valid

but use this with care: the API only supports to fetch  ALL Klassen, Teachers, ...

**Comment by Jan-Weigang** [comment]
oh my lord. I can't believe I absolutely overlooked this -.-
I spend like 2 hours a day in that document atm. Thank you for making me see the forest  :D
