### ISSUE TITLE
How to get homework or notifications 

### ISSUE THREAD

**Issue by LorendosCSharp** [python-webuntis/python-webuntis#58]
I was creating a Discord bot for my class but couldn't find anything about some extra features, like notifications or homework, etc.

The only thing that seemed to be what I wanted was class_reg_events (though I'm not sure if that's the right thing). However, I need more permissions for that, and I can't get them.

So, my question is: where can I find some extra information from my WebUntis account?"

**Comment by AugustH** [comment]
the official API is fully implemented in this lib. And the permissions are *strange* -- so the only chance is to google for the unofficial API e.g. BetterUntis

**Comment by crimsdings** [comment]
i wrote a solution https://github.com/python-webuntis/python-webuntis/issues/49#issuecomment-1916249549 here

> the official API is fully implemented in this lib. And the permissions are _strange_ -- so the only chance is to google for the unofficial API e.g. BetterUntis
